#!/usr/bin/env python3
"""
compare_models.py — Side-by-side evaluation of all locally run LLM models.

Walks papers/tg-roger-joshua/verdicts/<safe_tag>/*.json, recomputes the
classification metrics against the expert gold set (CATEGORIA REVISA),
and writes a single comparison artefact:

    papers/tg-roger-joshua/sections/_auto/models_comparison.tex
        — booktabs table with one row per model:
          Accuracy / Macro-P / Macro-R / Macro-F1 / N
    papers/tg-roger-joshua/sections/_auto/models_comparison.json
        — raw per-model metrics dicts (same shape as metrics.json), keyed
          by model_id.

USAGE
    bash containers/run.sh paper-data \\
        python papers/tg-roger-joshua/scripts/compare_models.py

    # restrict to a subset
    python papers/tg-roger-joshua/scripts/compare_models.py \\
        --only qwen2.5:14b-instruct llama3.1:8b-instruct

EXIT CODES
    0 = comparison written
    2 = fatal error (no verdicts / no gold overlap)
"""

from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

import evaluate as ev  # sibling module


PAPER = ev.PAPER
VERDICTS_DIR = ev.VERDICTS_DIR
OUT_DIR = ev.OUT_DIR
COMPARISON_JSON = OUT_DIR / "models_comparison.json"
COMPARISON_TEX = OUT_DIR / "models_comparison.tex"


def list_model_dirs(only: list[str]) -> list[Path]:
    if not VERDICTS_DIR.exists():
        raise FileNotFoundError(f"missing {VERDICTS_DIR} (run classify.py first)")
    dirs = sorted(p for p in VERDICTS_DIR.iterdir() if p.is_dir())
    if only:
        wanted = {s.replace(":", "_").replace("/", "_") for s in only}
        dirs = [p for p in dirs if p.name in wanted]
    return dirs


def any_verdict_model_id(dir_: Path) -> str:
    for f in sorted(dir_.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except Exception:
            continue
        mid = data.get("model_id")
        if mid:
            return mid
    return dir_.name  # fall back to sanitized dir name


def render_comparison_tex(rows: list[dict]) -> str:
    body_lines = []
    best_f1 = max(r["macro_f1"] for r in rows) if rows else 0.0
    for r in rows:
        bold = r["macro_f1"] >= best_f1 - 1e-9
        def cell(v: float) -> str:
            s = f"{v*100:.1f}"
            return f"\\textbf{{{s}}}" if bold else s
        body_lines.append(
            f"    \\texttt{{{r['model_id']}}} & "
            f"{cell(r['accuracy'])} & "
            f"{cell(r['macro_precision'])} & "
            f"{cell(r['macro_recall'])} & "
            f"{cell(r['macro_f1'])} & "
            f"{r['n']} \\\\"
        )
    body = "\n".join(body_lines)
    return f"""% Auto-generated by scripts/compare_models.py — do not edit.
\\begin{{table}}[t]
  \\centering
  \\caption{{Classification performance of the locally executed open-weight models against the expert gold set. Values are percentages; the best Macro-F1 row is in bold.}}
  \\label{{tab:llm-comparison}}
  \\begin{{tabular}}{{lrrrrr}}
    \\toprule
    \\textbf{{Model}} & \\textbf{{Acc.}} & \\textbf{{P}} & \\textbf{{R}} & \\textbf{{F1}} & \\textbf{{N}} \\\\
    \\midrule
{body}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", nargs="*", default=[],
                    help="Restrict to these Ollama model tags")
    args = ap.parse_args()

    try:
        model_dirs = list_model_dirs(args.only)
        gold = ev.load_gold()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2

    if not model_dirs:
        print(f"ERROR: no per-model verdict subdirs under {VERDICTS_DIR}.",
              file=sys.stderr)
        return 2

    rows: list[dict] = []
    full_metrics: dict[str, dict] = {}
    for d in model_dirs:
        verdicts = ev.load_verdicts(d)
        if verdicts.empty:
            print(f"  skip {d.name}: empty", file=sys.stderr)
            continue
        model_id = any_verdict_model_id(d)
        try:
            m = ev.compute_metrics(verdicts, gold, verbose=False)
        except ValueError as e:
            print(f"  skip {model_id}: {e}", file=sys.stderr)
            continue
        m["model_id"] = model_id
        full_metrics[model_id] = m
        rows.append({
            "model_id": model_id,
            "accuracy": m["accuracy"],
            "macro_precision": m["macro_precision"],
            "macro_recall": m["macro_recall"],
            "macro_f1": m["macro_f1"],
            "n": m["n"],
        })

    if not rows:
        print("ERROR: no usable per-model metrics.", file=sys.stderr)
        return 2

    rows.sort(key=lambda r: r["macro_f1"], reverse=True)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    COMPARISON_JSON.write_text(
        json.dumps({"models": full_metrics, "ranking": rows},
                   indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    COMPARISON_TEX.write_text(render_comparison_tex(rows), encoding="utf-8")

    header = f"{'model':40} {'Acc':>6} {'P':>6} {'R':>6} {'F1':>6} {'N':>4}"
    print(header)
    print("-" * len(header))
    for r in rows:
        print(f"{r['model_id'][:40]:40} "
              f"{r['accuracy']*100:6.1f} {r['macro_precision']*100:6.1f} "
              f"{r['macro_recall']*100:6.1f} {r['macro_f1']*100:6.1f} "
              f"{r['n']:>4}")
    print()
    print(f"Wrote {COMPARISON_TEX.relative_to(PAPER.parent.parent)}")
    print(f"Wrote {COMPARISON_JSON.relative_to(PAPER.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
