#!/usr/bin/env python3
r"""
render_confusion.py — Draw the confusion matrix as a TikZ figure.

Reads:
    papers/tg-roger-joshua/sections/_auto/metrics.json  (produced by evaluate.py)

Writes:
    papers/tg-roger-joshua/figures/_auto/confusion_matrix.tex

The output is a standalone TikZ picture intended to be \input{} from the
paper body. Cells are shaded proportionally to their share of the row
(per-gold normalization) so that diagonal dominance is immediately visible
regardless of class imbalance.

USAGE
    bash containers/run.sh paper-data \\
        python papers/tg-roger-joshua/scripts/render_confusion.py

EXIT CODES
    0 = figure written
    2 = missing metrics.json (run evaluate.py first)
"""

from __future__ import annotations
import json
import sys
from pathlib import Path


PAPER = Path(__file__).resolve().parent.parent
METRICS_JSON = PAPER / "sections" / "_auto" / "metrics.json"
OUT_TEX = PAPER / "figures" / "_auto" / "confusion_matrix.tex"


# Compact labels for the 23-term IEEE Thesaurus taxonomy so the matrix
# fits on a two-column IEEE page.
SHORT_LABELS = {
    "Information systems":            "IS",
    "Database management systems":    "DB",
    "Enterprise information systems": "EIS",
    "Web applications":               "Web",
    "Mobile applications":            "Mob",
    "Software engineering":           "SE",
    "Artificial intelligence":        "AI",
    "Machine learning":               "ML",
    "Natural language processing":    "NLP",
    "Image processing":               "IP",
    "Computer vision":                "CV",
    "Recommender systems":            "Rec",
    "Data mining":                    "DM",
    "Ontologies":                     "Ont",
    "Multi-agent systems":            "MAS",
    "Cybersecurity":                  "Sec",
    "Constraint programming":         "CP",
    "Complex networks":               "CN",
    "Internet of Things":             "IoT",
    "Gamification":                   "Gam",
    "Serious games":                  "SG",
    "E-learning":                     "EL",
    "Other":                          "Oth",
}


def _active_indices(cm: list[list[int]]) -> list[int]:
    """Return indices of rows/columns with any non-zero count.

    With 23 IEEE terms and a 111-project gold set, most labels have zero
    support; keeping every class would produce a sparse 23x23 matrix
    dominated by blanks. We restrict the figure to the union of classes
    that appear either in the expert gold column or in the LLM prediction
    row so the diagonal is legible.
    """
    n = len(cm)
    row_active = [i for i in range(n) if sum(cm[i]) > 0]
    col_active = [j for j in range(n) if sum(cm[i][j] for i in range(n)) > 0]
    return sorted(set(row_active) | set(col_active))


def render(metrics: dict) -> str:
    labels = metrics["labels"]
    cm = metrics["confusion_matrix"]
    n = metrics["n"]

    active = _active_indices(cm)
    sub_labels = [labels[k] for k in active]
    sub_cm = [[cm[i][j] for j in active] for i in active]

    row_totals = [sum(row) or 1 for row in sub_cm]
    shares = [[sub_cm[i][j] / row_totals[i] for j in range(len(sub_labels))]
              for i in range(len(sub_labels))]

    cell_w = 0.85  # cm; smaller than the old 2.2 since we have more columns
    cell_h = 0.55

    cells = []
    for i, row in enumerate(sub_cm):
        for j, val in enumerate(row):
            intensity = int(round(shares[i][j] * 60))
            text_color = "white" if shares[i][j] >= 0.55 else "black"
            if val == 0 and intensity == 0:
                fill = "gray!8"
            else:
                fill = f"blue!{intensity}"
            cells.append(
                f"    \\node[fill={fill}, minimum width={cell_w}cm, "
                f"minimum height={cell_h}cm, text={text_color}, "
                f"font=\\scriptsize] "
                f"at ({j*cell_w:.2f},{-i*cell_h:.2f}) {{{val}}};"
            )

    col_headers = []
    for j, label in enumerate(sub_labels):
        short = SHORT_LABELS.get(label, label[:4])
        col_headers.append(
            f"    \\node[font=\\bfseries\\tiny, rotate=60, anchor=west] "
            f"at ({j*cell_w:.2f},{cell_h*0.8:.2f}) {{{short}}};"
        )

    row_headers = []
    for i, label in enumerate(sub_labels):
        short = SHORT_LABELS.get(label, label[:4])
        row_headers.append(
            f"    \\node[font=\\bfseries\\scriptsize, anchor=east] "
            f"at ({-cell_w*0.20:.2f},{-i*cell_h:.2f}) {{{short}}};"
        )

    body = "\n".join(col_headers + row_headers + cells)
    n_active = len(sub_labels)
    n_hidden = len(labels) - n_active

    legend_pairs = [f"{SHORT_LABELS.get(lbl, lbl[:4])} = {lbl}"
                    for lbl in sub_labels]
    legend = "; ".join(legend_pairs)

    return f"""% Auto-generated by scripts/render_confusion.py — do not edit.
\\begin{{figure*}}[t]
  \\centering
  \\begin{{tikzpicture}}[every node/.style={{font=\\scriptsize}}]
{body}
  \\end{{tikzpicture}}
  \\caption{{Confusion matrix of the {{LLM}} classifier against the expert
  gold set ($N={n}$). Rows are expert labels ({{IEEE}} Thesaurus); columns
  are the {{LLM}}-predicted primary term. Cell shading is proportional to
  the share of each expert row; only the {n_active} labels with non-zero
  support are shown ({n_hidden} {{IEEE}} terms are unused in this
  evaluation). Abbreviations: {legend}.}}
  \\label{{fig:confusion-matrix}}
\\end{{figure*}}
"""


def main() -> int:
    if not METRICS_JSON.exists():
        print(f"ERROR: missing {METRICS_JSON} — run evaluate.py first.",
              file=sys.stderr)
        return 2

    metrics = json.loads(METRICS_JSON.read_text(encoding="utf-8"))
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text(render(metrics), encoding="utf-8")
    print(f"Wrote {OUT_TEX.relative_to(PAPER.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
